services:
  image-stylization-app:
    build: .
    container_name: image-stylization
    ports:
      - "8501:85  01"
    environment:
      - PYTHONUNBUFFERED=1
      - FORCE_CPU=0
    volumes:
      - .:/app
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G